In [5]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

#loading the dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#data cleanup

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [6]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
309395,Data Engineer,"Data Engineer, Data & Reporting","Zürich, Switzerland",via UBS - Talentify,Full-time,False,Switzerland,2023-03-17 17:36:32,False,False,Switzerland,NaN,NaN,NaN,UBS,"['sql', 'python', 'azure']","{'cloud': ['azure'], 'programming': ['sql', 'p..."
418639,Senior Data Engineer,Senior Data Engineer,"London, UK",via BeBee,Full-time,False,United Kingdom,2023-08-17 16:18:24,True,False,United Kingdom,NaN,NaN,NaN,Zalando,"['sql', 'java', 'python', 'aws', 'redshift']","{'cloud': ['aws', 'redshift'], 'programming': ..."
624247,Senior Data Scientist,Data Scientist / Senior Data Scientist,"İstanbul, Türkiye",via LinkedIn,Full-time,False,Turkey,2023-04-03 12:37:12,False,False,Turkey,NaN,NaN,NaN,Linktera,"['python', 'sql', 'oracle', 'hadoop', 'spark']","{'cloud': ['oracle'], 'libraries': ['hadoop', ..."
425282,Software Engineer,Middle Software Engineer,"Bogotá, Bogota, Colombia",via BeBee Colombia,Full-time,False,Colombia,2023-03-02 16:32:19,True,False,Colombia,NaN,NaN,NaN,AgileEngine,"['java', 'scala', 'aws', 'spark', 'kafka', 'sp...","{'cloud': ['aws'], 'libraries': ['spark', 'kaf..."
701066,Data Analyst,"Data Analyst - Part Time (Greater NYC Area, NY...",Anywhere,via Built In NYC,Part-time,True,"New York, United States",2023-09-22 02:59:54,True,False,United States,year,83200.0,NaN,Memorial Sloan Kettering Cancer Center,"['go', 'sql']","{'programming': ['go', 'sql']}"
22335,Senior Data Scientist,Senior Data Scientist,Anywhere,via LinkedIn,Full-time,True,Spain,2023-08-08 13:21:24,False,False,Spain,NaN,NaN,NaN,WeDoData,"['python', 'sql', 'bash', 'pandas', 'numpy', '...","{'libraries': ['pandas', 'numpy', 'scikit-lear..."
29648,Data Analyst,Data Analyst H/F,"Boulogne-Billancourt, France",via Indeed,Full-time,False,France,2023-11-14 13:37:24,False,False,France,NaN,NaN,NaN,Viveris,"['sql', 'python', 'r', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr..."
46598,Business Analyst,Commercial & Business Intelligence Analyst,"Geneva, Switzerland",via Central Illinois Proud Jobs,Full-time,False,Switzerland,2023-03-25 06:34:46,False,False,Switzerland,NaN,NaN,NaN,LHH,"['excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint']}"
318474,Business Analyst,Operational Performance Analyst,"Stockholm, Sweden",via LinkedIn,Full-time,False,Sweden,2023-04-06 17:12:15,False,False,Sweden,NaN,NaN,NaN,TUI,"['tableau', 'excel', 'powerpoint']","{'analyst_tools': ['tableau', 'excel', 'powerp..."
209274,Data Scientist,Data Scientist Faculty,"Washington, DC",via ZipRecruiter,Full-time,False,Georgia,2023-10-05 22:42:31,False,False,United States,NaN,NaN,NaN,Children's National Health System,"['mongodb', 'mongodb', 'r', 'python', 'scala',...","{'cloud': ['aws', 'azure', 'gcp', 'oracle'], '..."

In [7]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [8]:
df.index.name = 'job_index'

In [9]:
df.head(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,NaN,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,NaN,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [10]:
df.index.dtype

dtype('int64')

Reset_index()

In [11]:
df_usa = df[df['job_country']== 'United States']

In [12]:
df_usa.reset_index(inplace=True)
df_usa

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2,5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
3,6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
4,9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206287,785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
206288,785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
206289,785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
206290,785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
206291,785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

set_index()

In [13]:
df_usa.set_index('job_index', inplace = True)
df_usa

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

sort_index()

In [14]:
median_pivot = df_usa.pivot_table(values='salary_year_avg', index='job_title_short', aggfunc=['median', 'min', 'max'])

In [15]:
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0         35000.0        387460.0
Cloud Engineer                   116100.0         42000.0        221844.0
Data Analyst                      90000.0         25000.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Data Scientist                   130000.0         30000.0        960000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Analyst              110000.0         35360.0        425000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Senior Data Scientist            155000.0         55000.0        475000.0
Software Engineer                130000.0         48982.0        375000.0

In [16]:
median_pivot.sort_values(by=('median','salary_year_avg'),ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            155000.0         55000.0        475000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Data Scientist                   130000.0         30000.0        960000.0
Software Engineer                130000.0         48982.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Cloud Engineer                   116100.0         42000.0        221844.0
Senior Data Analyst              110000.0         35360.0        425000.0
Business Analyst                  90000.0         35000.0        387460.0
Data Analyst                      90000.0         25000.0        375000.0

In [17]:
median_pivot.sort_index()

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0         35000.0        387460.0
Cloud Engineer                   116100.0         42000.0        221844.0
Data Analyst                      90000.0         25000.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Data Scientist                   130000.0         30000.0        960000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Analyst              110000.0         35360.0        425000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Senior Data Scientist            155000.0         55000.0        475000.0
Software Engineer                130000.0         48982.0        375000.0